blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
]

krs_mekbat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("accounts/", include("war.urls", namespace="war")),
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(pattern_name='war:home')),
    # path("", include("blog.urls", namespace="blog")),
]

war/urls.py
from django.urls import path
    
from . import views, api, api_presence

app_name = 'war'
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("register/", views.register, name="register"),
    path("home/", views.home, name="home"),
    path('logout/', views.logout_user, name='logout'),
    path('krs_war/<slug>', views.krs_war, name='krs_war'),
    path('admin_control/', views.admin_control, name='admin_control'),
    path('show_qr/', views.show_qr, name="show_qr"),
    path('schedule_list/', views.schedule_list_view, name='schedule_list_view'),

    path('api/krs_war/<slug>', api.krs_war, name='api_krs_war'),
    path('api/presence/<api_type>', api_presence.api_handler, name="api_presence")
]

blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=20)
    date = models.DateField(default=timezone.now, blank=True)
    content = models.TextField(max_length=3000)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from .models import Post

def index(request):
    return render(request, "blog/home.html", {
        "posts" : Post.objects.order_by("-date")
    })

blog/templates/blog/_home.html
<html>

<head>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
    id="bootstrap-css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!------ Include the above in your HEAD tag ---------->

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

  {% load static %}
  <link rel="stylesheet" href="{% static 'war/css/home_style.css' %}">
  <link rel="stylesheet" href="{% static 'blog/css/home_style.css' %}">

  {% block head %}

  {% endblock head %}

</head>

<body>
  <div class="container">
    <br>


    <div class="row justify-content-center">
      <div class="col">
        <div class="card">
          <header class="card-header">
            <a href="{% url 'war:login' %}" class="float-right btn btn-outline-primary mt-1">Log in</a>
            {# <a href="{% url 'war:logout' %}" class="float-right btn btn-outline-primary mt-1 mr-3">QR Code</a> #}
            <h6 class="card-title mt-2">Laboratorium Simulasi dan Komputasi</h6>
          </header>
          <article class="card-body">
            {% block content %}
            {% endblock content %}
          </article> <!-- card-body end .// -->
        </div> <!-- card.// -->
      </div> <!-- col.//-->

    </div> <!-- row.//-->


  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
    crossorigin="anonymous"></script>
  <!--container end.//-->
</body>
<footer class="text-center">
  {# <div class="pt-3"><img style="max-width: 10%" src="{% static 'war/img/logo.png' %}" alt=""></div> #}
  <div class="pt-5 pl-1 pr-1">
    <h6>Laboratorium Simulasi dan Komputasi</h6>
  </div>
  <div class="text-center">
    <p class="pb-2" style="font-size: small; margin-bottom: 0;">
      Developed by <a href="https://www.linkedin.com/in/fakhricrofi/" style="color: blue;">FCR</a>. Copyright © 2026
    </p>
  </div>
</footer>

</html>

blog/templates/blog/home.html
{% extends "blog/_home.html" %}
{% load static %}

{% block head %}
<title>Home - Lab Simulasi dan Komputasi</title>
{% endblock head %}

{% block content %}

{% for post in posts %}
<article class="post">
    <h4 class="post-title">{{ post.title }}</h4>
    <p class="post-meta">Posted by <span class="post-author">{{ post.author }}</span> on <span class="post-date">{{
            post.date }}</span></p>
    <div class="post-content">
        {{ post.content|linebreaks }}
    </div>
</article>
{% endfor %}

{% endblock content %}